### ISSUE TITLE
"Permanently delete" popup affirmation is illegible

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#177]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Installed from `pop-gtk-theme_3.99.1.1533659735.18.04.92c7ad1_all.deb`
Running `Pop-4`

**Actual issue**
When attempting to permanently delete something from nautilus, the popup warning me that the folder is going to be deleted has an "Delete" button that is not legible (white on white)

![permanentdelete](https://user-images.githubusercontent.com/7460774/43804104-163749a0-9a58-11e8-9a8b-da99b71a8d86.png)

**Comment by isantop** [comment]
![screenshot from 2018-08-07 16-45-58](https://user-images.githubusercontent.com/5883565/43806479-6722d07e-9a61-11e8-9b99-198959e16a7b.png)

Edited

**Comment by isantop** [comment]
Fixed in `master_cosmic`

**Comment by Mancooo** [comment]
This bug is back. Seeing this on Pop-dark, latest git:

 * Distribution - Fedora release 29 (Twenty Nine)
 * Gtk+ 3.0 version - 3.24.1-1.fc29
 * Desktop environment - Gnome
 * Pop version - Pop!_GNOME+ Version 4.0.2 

![screenshot from 2019-01-17 23-01-26](https://user-images.githubusercontent.com/12864999/51352444-e5e27a00-1aad-11e9-8334-548829bb5250.png)
