### ISSUE TITLE
Selected row > buttons have white text on white bg

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#31]
Demonstrable in AppCenter's update page; select a row with a button and the text on the button is unreadable

**Comment by isantop** [comment]
How does one get a row selected? Clicking on a row sends me to the app's page in AppCenter.

**Comment by WatchMkr** [comment]
@cassidyjames @isantop I think this was fixed with an application flow change @jackpot51 made. Clicking back no longer highlights the application that was clicked.

@cassidyjames should we propose that change to the elementary team?

**Comment by isantop** [comment]
@WatchMkr that doesn't necessarily mean the bug is fixed, and it's still a valid issue. Discussion about the pop-shop stuff should probably happen over there.

**Comment by cassidyjames** [comment]
@WatchMkr yeah we should propose that change, but mostly due to semantics versus theming. This is still an issue in the stylesheet that should get fixed eventually, but I agree that it's a lower priority now that it's not visible anywhere in practice as far as I know.

**Comment by ahmadaidil** [comment]
look at screenshot below.
![alt text](http://preview.ibb.co/jWKxd6/Screenshot_from_2017_10_22_14_48_26.png "Logo Title Text 1")
the app title color is white on white background.

**Comment by isantop** [comment]
@ahmadaidil That screenshot is very small. Can you upload the original resolution version? I can't tell what text you're talking about.

**Comment by isantop** [comment]
The original issue is now fixed in the version-3 branch. It will be released along with the next version of the theme. @ahmadaidil Feel free to open a new issue with your bug.
